name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest,ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Archive bin folder
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ runner.os }}
          path: |
            ${{github.workspace}}/target/release
  package:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Download Linux
        uses: actions/download-artifact@v2
        with:
          path: ${{github.workspace}}/linux
          name: build-Linux
      - name: Download Windows
        uses: actions/download-artifact@v2
        with:
          path: ${{github.workspace}}/windows
          name: build-Windows
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Release"
          prerelease: false
          files: | 
            **/windows/*.exe
            **/linux/tmbook
